sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: dbuserdbuser

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t5tU2nRMSuFY9DtRAWn
    access-key-secret: FtES2IXio4LlOD8RHyAuP6uJWQIMGv
    bucket-name: javaweb-ai123

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0

  wechat:
    appid: wx3e114efe945bb305
    secret: f54613d4d718e79e1f5821bd44a08a7d

  shop:
    address: 成都市郫都区天骄路57号
  baidu:
    ak: 5WkYg2FdNsvvml0Tm0bAnvztsk93cuZf